In [7]:
batch_size = 8

In [8]:
import tensorflow as tf
from numpy.random import RandomState

In [12]:
w1 = tf.Variable(tf.random_normal([2, 3], stddev = 1, seed = 1))
w2 = tf.Variable(tf.random_normal([3, 1], stddev = 1, seed = 1))

x = tf.placeholder(tf.float32, shape = (None, 2), name = 'x-input')
y_ = tf.placeholder(tf.float32, shape = (None, 1), name = 'y-input')

#定义前向传播过程
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

#定义损失函数和反向传播算法
y = tf.sigmoid(y)
cross_entropy = -tf.reduce_mean(
y_ * tf.log(tf.clip_by_value(1 - y, 1e-10, 1.0)))
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

#通过随机数生成一个模拟数据集
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size, 2)
Y = [[int(x1 + x2 < 1)]for (x1, x2) in X]

#创建会话
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(w1))
    print(sess.run(w2))
    
    STEPS = 5000
    for i in range(STEPS):
        start = (i * batch_size) % dataset_size
        end = min(start + batch_size, dataset_size)
        
        sess.run(train_step, feed_dict = {x:X[start:end], y_:Y[start:end]})
        if i% 1000 ==0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict = {x:X, y_:Y})
            print("After %d training steps , cross entropy on all data is %g"%
                 (i, total_cross_entropy))
    print(sess.run(w1))
    print(sess.run(w2))

[[-0.81131822  1.48459876  0.06532937]
 [-2.4427042   0.0992484   0.59122431]]
[[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]
After 0 training steps , cross entropy on all data is 0.827855
After 1000 training steps , cross entropy on all data is 0.196914
After 2000 training steps , cross entropy on all data is 0.0673856
After 3000 training steps , cross entropy on all data is 0.0349004
After 4000 training steps , cross entropy on all data is 0.0217244
[[-0.61989635  0.1288085   2.93862367]
 [-2.14299536 -1.11871612  3.57239819]]
[[ 0.47654247]
 [ 1.24429548]
 [-2.59359407]]
